# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff8eb8b3ec01067db6271bf949b002ffac7f1b702932d4594a6ce7419f3a3dcd49733a034745c5cac76a3395ca931e96ab3bb9445b89119438599e0bdb1362b0

test:
  secret_key_base: 3d6a1a05f3460ee0cc0256d05c246f448abed8462972ad789811548efc5622f63606d42ad61f1137988f6478efe9415b020a4590072234024873de1bde41f651

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
